spring:
  application:
    name: lazuly-email
app:
  host: ${HOST}
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${HOST}:8761/eureka/
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
mailjet:
  apiKey: ${MAILJET_API}
  secret: ${MAILJET_SECRET}
  from:
    email: mpasut@wolla.com.ar
    name: Lázuly
---
spring:
  profiles: developer
app:
  secret: aidafrancoygeorgelosamo
server:
  port: 8080

---
spring:
  profiles: staging
app:
  secret: ${INTERNAL_SECRET}
server:
  port: ${PORT}